### ISSUE TITLE
Label and input area in GUI not lined up correctly

### ISSUE THREAD

**Issue by ttstarck** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#15]
Labels belonging to an input area are slightly too low. Need to move them up slightly. - 100 points

**Comment by JohnUCSB** [comment]
F16 OK (100 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-utilities-bac-calculator/pull/24
