### ISSUE TITLE
Incorrect BAC message

### ISSUE THREAD

**Issue by hduransoto** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#23]
When blood alcohol content is between 0.126 and 0.129, the BAC calculator displays the incorrect symptoms/Impairments. 

If BAC is within that range, the part of the message displayed is:            
Symptoms/Impairment: Not Recommended! Onset of coma. Possible death due to respiratory arrest.

@JohnUCSB

**Comment by JohnUCSB** [comment]
F16 OK (50 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-utilities-bac-calculator/pull/24
