### ISSUE TITLE
CalculatorTest.java doesn't compile.

### ISSUE THREAD

**Issue by hduransoto** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#25]
After fixing issue #17, CalculatorTest.java doesn't compile because in order to add alcohol brands, we had to add more parameters to BAC method in Calc.java. Now we need to make new calculations in CalculatorTest.java in order to get the correct expected result with the new parameters we added.

@JohnUCSB 
200 pts?

**Comment by JohnUCSB** [comment]
F16 OK (200 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-utilities-bac-calculator/pull/24
