### ISSUE TITLE
Refactor the code so that each matching label and text field have their own class file. 250 pts

### ISSUE THREAD

**Issue by hduransoto** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#29]
Each matching textfield and label in BACPanel.java should be separated into different class files. This will make the code easier to read and to find a specific label rather than having to scroll through 300 lines of code. BACPanel.java should be used to append all labels in a frame and to implement the actionPerformed method.

200 pts? 300 pts?

**Comment by JohnUCSB** [comment]
F16 OK (250 pts)

**Comment by john-lau** [comment]
W18 OK. 250 pts
