### ISSUE TITLE
Clear after each run

### ISSUE THREAD

**Issue by PazZaitGivon** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#3]
currently new text added at each run but it is confusing what it is responding to. Fix this by : reprinting the information the user entered at the start of each run

Estimated ~ 50 points

If you are more ambitious make it also so that only the most recent one relevant  stays available

Estimated an additional 100 points

**Comment by nickkpoon** [comment]
Both parts resolved.

**Comment by PazZaitGivon** [comment]
great!
