### ISSUE TITLE
There are a lot more type of beers, wine, and hard liquor to be added. 50 pts

### ISSUE THREAD

**Issue by hduransoto** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#33]
There are a lot more brands of beers, types of wine, and type of liquor that can be added to the list and they all have different alcohol content.

**Comment by JohnUCSB** [comment]
3 more brands for each type of liquor.
F16 OK (100 pts)

**Comment by john-lau** [comment]
W18 OK. 50 pts

**Comment by john-lau** [comment]
closed with pull request #44
