### ISSUE TITLE
Alphabetize all the options in the text area. 100 pts

### ISSUE THREAD

**Issue by hduransoto** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#34]
The labels circled all need to have the options in the textfields to be alphabetized. 
![bacpic](https://cloud.githubusercontent.com/assets/22375784/20786912/db110e62-b75d-11e6-92d2-739b560b4194.png)

**Comment by JohnUCSB** [comment]
Keep the options always sorted. Once the list gets much longer, we can also add filters.
F16 OK (100 pts).

**Comment by john-lau** [comment]
W18 OK. 100 pts

**Comment by john-lau** [comment]
closed with pull request #44
