### ISSUE TITLE
Fix README

### ISSUE THREAD

**Issue by rrthirumulu** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#4]
Fix README to include additional information.
Information includes: developer information, screenshots of program, build/execute instructions 

Suggested points: 75

**Comment by PazZaitGivon** [comment]
possible, if super extensive, otherwise, more likely to be around 50 points

**Comment by nickkpoon** [comment]
Resolved.

**Comment by PazZaitGivon** [comment]
much better, worth the full 75
