### ISSUE TITLE
Clean up code

### ISSUE THREAD

**Issue by rrthirumulu** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#8]
Certain portions of the code are repetitive, especially in BACMessage.java and Calc.java. Clean up code to make it easier to read/understand.

**Comment by PazZaitGivon** [comment]
Good issue ~ 150 points

**Comment by JohnUCSB** [comment]
F16 OK (150 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-utilities-bac-calculator/pull/24
