### ISSUE TITLE
Estimate amount of drinks user can have

### ISSUE THREAD

**Issue by rrthirumulu** [UCSB-CS56-Projects/cs56-utilities-bac-calculator#9]
Leave an option for the user, if under the drinking limit, to specify the amount of drinks (accounting for conversion between all types of drinks) he/she can have within a certain time limit(provided by user) while still being able to drive legally.

**Comment by PazZaitGivon** [comment]
Looks good

**Comment by JohnUCSB** [comment]
F16 OK (200 pts)

**Comment by JohnUCSB** [comment]
https://github.com/UCSB-CS56-Projects/cs56-utilities-bac-calculator/pull/24
